hydra:
  searchpath:
    - pkg://verl.trainer.config

defaults:
  - ppo_trainer
  - _self_


custom_reward_function:
  path: env_tuning/alfworld_reward.py
  name: compute_score


data:
  max_prompt_length: 2048
  max_response_length: 512
  return_raw_chat: True

actor_rollout_ref:
  hybrid_engine: True
  rollout:
    name: sglang
    multi_turn:
      enable: True
      max_turns: 60
      interaction_config_path: "env_tuning/config/alfworld/interaction_config.yaml"
      format: qwen
    max_model_len: 8192
  actor:
    optim:
      lr: 1e-6

critic:
  grad_clip: 1.0
  cliprange_value: 0.5

algorithm:
  gamma: 1.0
  lam: 1.0
  adv_estimator: grpo
  use_kl_in_reward: False
  kl_penalty: kl
  kl_ctrl:
    type: fixed
    kl_coef: 0.0

reward_model:
  reward_manager: bfcl

trainer:
  critic_warmup: 0
